#!/usr/bin/env python3
"""Generate the checked-in 1-bit dashboard emoji atlas; not part of normal builds.

Requires Pillow, freetype-py and uharfbuzz. Inputs are pinned and hash-checked.
Usage: python scripts/build_dashboard_emoji.py [--download]
"""
import argparse
import hashlib
from pathlib import Path
import urllib.request

import freetype
import uharfbuzz as hb
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "build/emoji-source"
OUT = ROOT / "src/dashboard/emoji"
COMMIT = "8b0a1d0f5983c89bc2b93f1b5fb55f9e252744b5"
INPUTS = {
    "NotoEmoji.ttf": (
        f"https://raw.githubusercontent.com/google/fonts/{COMMIT}/ofl/notoemoji/NotoEmoji%5Bwght%5D.ttf",
        "de6c18832938afc99caf132b39d6a30a19bac7f2e812e28db2535b4608d27551"),
    "OFL.txt": (
        f"https://raw.githubusercontent.com/google/fonts/{COMMIT}/ofl/notoemoji/OFL.txt",
        "500bb1ccf43df7bbb522112f9133a52b16e1c35e809632f5d8609b179152de5b"),
    "emoji-test.txt": (
        "https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt",
        "1d8a944f88d7952f7ef7c5167fef3c67995bcae24543949710231b03a201acda"),
}
SIZE = 32


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--download", action="store_true")
    args = parser.parse_args()
    SOURCE.mkdir(parents=True, exist_ok=True)
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (url, expected) in INPUTS.items():
        path = SOURCE / name
        if args.download and not path.exists():
            path.write_bytes(urllib.request.urlopen(url, timeout=60).read())
        if hashlib.sha256(path.read_bytes()).hexdigest() != expected:
            raise RuntimeError(f"Input checksum mismatch: {name}")

    font = hb.Font(hb.Face((SOURCE / "NotoEmoji.ttf").read_bytes()))
    font.set_variations({"wght": 400})
    face = freetype.Face(str(SOURCE / "NotoEmoji.ttf"))
    face.set_var_design_coords([400])
    face.set_pixel_sizes(0, 128)
    # Index zero is the visible fallback for sequences absent from the pinned font.
    missing = Image.new("L", (SIZE, SIZE))
    draw = ImageDraw.Draw(missing)
    draw.rounded_rectangle((3, 3, 28, 28), radius=3, outline=255, width=2)
    draw.line((10, 10, 21, 21), fill=255, width=2)
    draw.line((10, 21, 21, 10), fill=255, width=2)
    bitmaps = [missing.point(lambda p: 255 if p >= 128 else 0, mode="1").tobytes()]
    glyph_ids = {}
    entries = {}
    unsupported = []
    for line in (SOURCE / "emoji-test.txt").read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split(";", 1)
        text = "".join(chr(int(cp, 16)) for cp in fields[0].split())
        buf = hb.Buffer()
        buf.flags = hb.BufferFlags.REMOVE_DEFAULT_IGNORABLES
        buf.add_str(text)
        buf.guess_segment_properties()
        hb.shape(font, buf)
        infos = buf.glyph_infos
        if len(infos) != 1 or infos[0].codepoint == 0:
            entries[text.encode("utf-8")] = 0
            unsupported.append(fields[0].strip())
            continue
        gid = infos[0].codepoint
        if gid not in glyph_ids:
            face.load_glyph(gid, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_NO_HINTING)
            bitmap = face.glyph.bitmap
            raw = Image.frombytes("L", (bitmap.width, bitmap.rows), bytes(bitmap.buffer), "raw", "L", bitmap.pitch)
            bounds = raw.getbbox()
            if not bounds:
                raise RuntimeError(f"Empty emoji glyph: {gid}")
            raw = raw.crop(bounds)
            raw.thumbnail((SIZE - 2, SIZE - 2), Image.Resampling.LANCZOS)
            tile = Image.new("L", (SIZE, SIZE))
            tile.paste(raw, ((SIZE - raw.width) // 2, (SIZE - raw.height) // 2))
            packed = tile.point(lambda p: 255 if p >= 112 else 0, mode="1").tobytes()
            assert len(packed) == SIZE * SIZE // 8
            # Monochrome skin tones and presentation variants can share artwork.
            if packed not in bitmaps:
                bitmaps.append(packed)
            glyph_ids[gid] = bitmaps.index(packed)
        entries[text.encode("utf-8")] = glyph_ids[gid]

    pool = bytearray()
    records = []
    for key, glyph in sorted(entries.items()):
        records.append((len(pool), glyph))
        pool.extend(key + b"\0")
    assert len(records) < 65535 and len(bitmaps) < 65535
    assert max(map(len, entries)) < 192

    def array(name, data):
        rows = ["  " + ",".join(f"0x{x:02x}" for x in data[i:i + 24]) + "," for i in range(0, len(data), 24)]
        return f"static constexpr uint8_t {name}[] = {{\n" + "\n".join(rows) + "\n};\n"

    output = "// Generated by scripts/build_dashboard_emoji.py; do not edit.\n"
    output += "// Noto Emoji (SIL OFL 1.1); see OFL.txt and README.md.\n"
    output += array("KEYS", pool)
    output += "static constexpr Entry ENTRIES[] = {\n"
    output += "\n".join(f"  {{{offset}, {glyph}}}," for offset, glyph in records) + "\n};\n"
    output += array("BITMAPS", b"".join(bitmaps))
    (OUT / "Atlas.inc").write_text(output, encoding="utf-8", newline="\n")
    (OUT / "OFL.txt").write_bytes((SOURCE / "OFL.txt").read_bytes())
    (SOURCE / "unsupported.txt").write_text("\n".join(unsupported), encoding="utf-8")
    print(f"{len(entries)} sequences, {len(entries) - len(unsupported)} supported, {len(unsupported)} fallback; "
          f"{len(bitmaps)} unique tiles, {len(pool) + len(records) * 8 + len(bitmaps) * 128} atlas bytes")
    # A raster proof uses the exact packed data embedded in firmware.
    samples = ["📚", "💼", "🏠", "✅", "🔥", "❤️", "😀", "👩‍💻", "👍🏽", "🇹🇭", "🛒", "🎯"]
    proof = Image.new("1", (len(samples) * 48, 48), 1)
    for i, sample in enumerate(samples):
        tile = Image.frombytes("1", (SIZE, SIZE), bitmaps[entries[sample.encode("utf-8")]])
        proof.paste(tile.point(lambda p: 0 if p else 255), (i * 48 + 8, 8))
    proof.resize((len(samples) * 96, 96)).save(SOURCE / "proof.png")


if __name__ == "__main__":
    main()
